language: cpp
compiler:
  - gcc
install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev
  - sudo apt-get install libcppunit-dev
script:
  - qmake -project
  - qmake CPPUnitTesting.pro
  - make
  - ./$TRAVIS_BUILD_DIR/CPPUnitTesting

